# pre-commit autoupdate --freeze
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args:
          - -b main
          - -b master
          - -b develop
          - -p support/*

      # Common errors
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: CHANGELOG.md
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

      # Security
      - id: detect-private-key
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --args=--module
      - id: terraform_docs
        args:
          - --args=--show=all
      - id: terraform_validate
      - id: terraform_checkov
        stages: [pre-push]
        args:
          - --args=--quiet
          - --args=--compact
          - --args=--external-checks-dir /.pre-commit/checkov/external_checks
          - --args=--external-modules-download-path /.pre-commit/checkov/external_modules
          - --args=--skip-path .pre-commit
          - --args=--skip-path .vscode
          - --args=--download-external-modules true
          - --args=--enable-secret-scan-all-files
          # - --args=--config=__GIT_WORKING_DIR__/.checkov.yml
          # - --args=--create-config true
